### PR TITLE
Read avset informatino from machineset field

### PR DESCRIPTION
**Pull request by kon-angelo**
**What this PR does / why we need it**:

MCM was reading the information from a deprecated field in the machine class. This PR fixes the issue, while also providing support for the VMO vm types.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fix an issue where the availability set information was not transported properly on the driver. It also added support for VMO machines.
```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
/lgtm

**Review by prashanth26 — COMMENTED** [review]
Thanks for this fix @kon-angelo.

/assign @AxiomSamarth 
PTAL.

**Review by prashanth26 — APPROVED** [review]

**Comment by dkistner** [comment]
FYI: We will create a hotfix for that on `v0.3.0`

**Pull request merged**
