### PR TITLE
Add support for vm boot diagnostic profile

### LINKED ISSUE #104: Optionally Enable boot diagnostics for Azure VM prior to startup
**What would you like to be added**:
When launching an Azure VM, enable boot diagnostics. See https://learn.microsoft.com/en-us/cli/azure/vm/boot-diagnostics?view=azure-cli-latest

**Why is this needed**:
Good for investigating Azure VM startup failures.

### PR DESCRIPTION
**Pull request by hebelsan**
**What this PR does / why we need it**:

- Add support to enable vm boot diagnostics

**Which issue(s) this PR fixes**:
Fixes #104 

**Release note**:

```improvement user
Machine-Controller-Manager Provider-Azure now supports enabling of vm boot diagnostics. 
```

### CODE REVIEW

**Comment by hebelsan** [comment]
That's actually exactly how my first [commit](https://github.com/gardener/machine-controller-manager-provider-azure/pull/136/commits/a63cd653e34a50903771c63edef4ab63f4649c26) of this PR looked like :D
I thought it would be less complex and more talkative to always add the profile with default enabled=false, but I can see your point too.

**Comment by rishabh-11** [comment]
One question @hebelsan. Did you test this PR by checking if this works as expected?

**Comment by hebelsan** [comment]
@rishabh-11 yes, I've tested it manually.

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
can you add a validation for the diagnostics profile? If it is enabled, the `storageURI` cannot be empty, right?

**Comment by hebelsan** [comment]
If storageURI us not specified azure managed storage will be used, which is actually the preferred option.
This is documented as comment in the [providerSpec](https://github.com/gardener/machine-controller-manager-provider-azure/pull/136/files#diff-ee2c8c367cc2ea8c73e39f370ea450d41e586126e59aee94704cdc79077de8e8R278)

**Review by rishabh-11 — APPROVED** [review]
/lgtm

**Pull request merged**
